### PR TITLE
Add unit tests for input part of tags autocomplete

### PR DESCRIPTION
**Pull request by sharikovvladislav**

### CODE REVIEW

**Comment by rajesh-kannan** [comment]
i tried to run jest in your project, but it some tests fail in user-info.spec. Can you check once?

**Comment by sharikovvladislav** [comment]
What output did you get? I will check it in a few days.

вс, 7 янв. 2018 г., 15:06 rajesh-kannan <notifications@github.com>:

**Comment by sharikovvladislav** [comment]
@rajesh-kannan so I have this:

```
svlad at sharikovvlad in ~/dev/ng2-diary-book on feature/add-some-tests [$]
$ git pull
Already up-to-date.

svlad at sharikovvlad in ~/dev/ng2-diary-book on feature/add-some-tests [$]
$ rm -rf node_modules/

svlad at sharikovvlad in ~/dev/ng2-diary-book on feature/add-some-tests [$]
$ yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > angularfire2@4.0.0-rc0" has incorrect peer dependency "firebase@^3.6.6".
warning "@angular/cli > license-webpack-plugin@1.1.0" has unmet peer dependency "webpack-sources@>= 1.0.0".
[4/4] 📃  Building fresh packages...
✨  Done in 14.49s.

svlad at sharikovvlad in ~/dev/ng2-diary-book on feature/add-some-tests [$]
$ yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.63s.

svlad at sharikovvlad in ~/dev/ng2-diary-book on feature/add-some-tests [$]
$ yarn test
yarn run v1.3.2
$ jest
 PASS  src/app/shared/pipes/markdown.spec.ts
 PASS  src/app/diary/components/diary.spec.ts
 PASS  src/app/core/components/user-info.spec.ts
 PASS  src/app/core/features/components/tags-autocomplete/components/input.spec.ts

Test Suites: 1 skipped, 4 passed, 4 of 5 total
Tests:       3 skipped, 22 passed, 25 total
Snapshots:   7 passed, 7 total
Time:        4.236s
Ran all test suites.
✨  Done in 5.08s.
```

So, looks like everything is working on this branch.

What is your current branch? Do you have latest changes (git pull)? 
If yes, then: what is your
1) os
2) node ver
3) npm ver

?

**Comment by sharikovvladislav** [comment]
@rajesh-kannan any news?

**Pull request merged**
